[workspace]
resolver = "2"

members = [
    "axorigin",
    "axhal", "axconfig", "spinlock", "axsync", "page_table", "axalloc", "axruntime", "axstd", "axlog", "axdtb", "buddy_allocator", "bitmap_allocator", "axtask", "handler_table",
]

[profile.release]
lto = true
