[package]
name = "axtask"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
axhal = { path = "../axhal" }
axconfig = { path = "../axconfig" }
axsync = { path = "../axsync" }
spinlock = { path = "../spinlock" }
kernel_guard = { path = "../kernel_guard" }
